
# GitHub Actionsの名前を設定
name: Build

# ワークフローの名前
run-name: Build App

on:
  push: 
    branches: [develop]

jobs:
# jobの名前を設定
  build:
  # runs-on でランナーを指定
    runs-on: macos-latest

# stepsでActionを実行
    steps:
      - name: Print Build Start Message
        run: echo "start build process"
    # 既存のActionを利用して、リポジトリからソースコードをフェッチ
      - uses: actions/checkout@v4
    # 利用できるXcodeバージョンを確認
      - name: List available Xcode versions
        run: ls /Applications | grep Xcode
    # Xcodeのバージョンを指定
      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.2.app
    # アプリをビルドしてバイナリ作成
      - name: Application Build
      # xcodebuildというビルドツールを使いbuild, test, archiveなどを実行できる
        run: |
          xcodebuild \
            -project SampleApp.xcodeproj \
            -scheme SampleApp \
            -sdk iphonesimulator \
            build
# ビルド完了後のメッセージ出力（試しにjobを2つ定義したいだけ）
  notify:
    runs-on: macos-latest
    needs: build
    steps:
      - name: Notify Build Complete
        run: echo "Build Complete!"
    

