name: Update Version

run-name: version update for ${{github.event.pull_request.head.ref}}

on:
  pull_request:
    branches:
      - 'main'
    types:
      - closed

jobs:
  extract_release_version:
    if: | 
      github.event.pull_request.merged == true &&
      github.event.pull_request.base.ref == 'main' &&
      startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: macos-latest
    outputs:
      release_version: ${{steps.extract_version.outputs.release_version}} 
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Extract version from release branch
        id: extract_version
        run: |
          BRANCH_NAME="${{github.event.pull_request.head.ref}}"
          EXTRACT_VERSION="${BRANCH_NAME#release/}"
          echo "release_version=$EXTRACT_VERSION" >> $GITHUB_OUTPUT

  add_tag:
    needs: extract_release_version
    runs-on: macos-latest
    steps:
      - name: dummy action
        run: echo 'completed add tag'
