name: Update Version

run-name: version update for ${{github.event.pull_request.head.ref}}

on:
  pull_request:
    branches:
      - 'main'
    types:
      - closed

jobs:
  extract_release_version:
    if: | 
      github.event.pull_request.merged == true &&
      github.event.pull_request.base.ref == 'main' &&
      startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: macos-latest
    outputs:
      release_version: ${{steps.extract_version.outputs.release_version}} 
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Extract version from release branch
        id: extract_version
        run: |
          BRANCH_NAME="${{github.event.pull_request.head.ref}}"
          EXTRACT_VERSION="${BRANCH_NAME#release/}"
          echo "release_version=$EXTRACT_VERSION" >> $GITHUB_OUTPUT
      - name: print release version
        run: echo "release version is ${{steps.extract_version.outputs.release_version}}"

  version_increment:
    needs: extract_release_version
    runs-on: macos-latest
    outputs:
        current_version: ${{steps.current_app_version.outputs.current_version}}
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Check Xcode version
        run: xcodebuild -version
      - name: List available Xcode versions
        run: ls /Applications | grep Xcode
      - name: select xcode version
        run: sudo xcode-select -s '/Applications/Xcode_16.2.app/Contents/Developer'
      - name: build app
        run: |
          xcodebuild \
            -project SampleApp.xcodeproj \
            -scheme SampleApp \
            -sdk iphonesimulator \
            build
      - name: current directory 
        run: ls -a
      - name: read current app version from Info.plist
        id: current_app_version
        run: |
          CURRENT_VERSION=$(/usr/libexec/PlistBuddy -c "Print ApplicationProperties:CFBundleShortVersionString" ./SampleApp/Info.plist)
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
      - name: print current app version
        run: echo current app version is ${{steps.current_app_version.outputs.current_version}}


