name: Update Version

run-name: update to 1.0.0

on:
  push:
    branches:
      - develop

jobs:
  agvtool_update:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
