name: Update Version

run-name: update to 1.0.1

on:
  pull_request:
    branches:
      - 'main'
    types:
      - closed

jobs:
  agvtool_update:
    if: | 
      github.event.pull_request.merged == true &&
      github.event.pull_request.base.ref == 'main' &&
      startsWith(github.event.pull_request.base.ref, 'release/')
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: checkout completed
        run: echo "Completed Code Checkout"

  add_tag:
    needs: agvtool_update
    runs-on: macos-latest
    steps:
      - name: dummy action
        run: echo 'completed add tag'
